// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygirksildmlblehdlpet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnaXJrc2lsZG1sYmxlaGRscGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjE2MzYsImV4cCI6MjA2MzYzNzYzNn0.V_VSph8gJmX8SY2i8kTNIGeJZT7N5jYW0Ma8auynStY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);